apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: j9jasna25-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:004d611b2acb72415b3c6ca58010b9e5cc12c971@sha256:32b25770f0ab26be7dde4e7793dba6acabd6e270871451ca0c6f92aeb5a0d9cb
          name: container-image
